### ISSUE TITLE
fix mobile code rendering issue

### ISSUE THREAD

**Issue by 21han** [21han/blog#17]

**Comment by 21han** [comment]
related to https://github.com/adityatelange/hugo-PaperMod/issues/828

I didn't fix the issue entirely on my end but removing the code language hinting at least worked. It is just that I lost syntax highlighting for `.yml`

**Comment by bglw** [comment]
Hi!

This bug can be traced back to this iOS issue with flex and font sizing: https://stackoverflow.com/questions/38346494/why-is-flex-affecting-font-size-on-ios

Adding the following styles to your site will fix this bug and allow to you use the default Chroma highlighting in Hugo:

```
/* Fixes iOS font sizing anomaly */
code {
    text-size-adjust: 100%;
    -ms-text-size-adjust: 100%;
    -moz-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
```
